name: beast2
owner: iuc
categories:
- Phylogenetics
description: "BEAST 2: Bayesian Evolutionary Analysis Sampling Trees"
long_description: BEAST 2 is a software platform for Bayesian evolutionary analysis of molecular sequences using MCMC. It is designed for phylogenetic inference, divergence time estimation, and testing evolutionary hypotheses based on genetic data.
homepage_url: https://www.beast2.org/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/tools/beast2
type: unrestricted
suite:
  name: "suite_beast2"
  description: "A suite of tools for BEAST 2 in Galaxy"
  type: repository_suite_definition
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the BEAST 2 tool suite: {{ tool_name }}"