---
categories:
  - Sequence Analysis
description: Tool to find ligation pairs in alignment data
homepage_url: https://pairtools.readthedocs.io
long_description: >
  A simple and fast command-line tool to process sequencing data from a Hi-C experiment
name: pairtools_parse
owner: iuc
remote_repository_url: "https://github.com/galaxyproject/tools-iuc/tree/main/tools/pairtools_parse"
type: unrestricted