name: tbprofiler 
owner: iuc
description: Processes M. tuberculosis sequence data to infer strain type and identify known drug resistance markers. 
long_description: |
  TB-Profiler aligns reads to the H37Rv reference using bowtie2, BWA-MEM, BWA-MEM2 or minimap2 and then calls 
  variants (by default using freebayes). These variants are then compared to a drug-resistance database to
  predict drug resistance. For Illumina data the number of reads supporting the drug resistance variant
  is also reported.
homepage_url: https://github.com/jodyphelan/TBProfiler
remote_repository_url: https://github.com/galaxyproject/tools-iuc/blob/master/tools/tb-profiler
type: repository_suite_definition
categories:
  - Sequence Analysis
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} (from the TBProfiler tool suite)"
#repositories:
#  tb_profiler_profile:
#    description: "Predict M. tuberculosis lineage and drug resistance from sequences in FASTQ or BAM"
#    long_description: |
#      This tool computes a drug resistance and lineage profile from M. tuberculosis whole genome
#      sequencing (WGS) data. 
#
#      The pipeline aligns reads to the H37Rv reference using bowtie2, BWA or minimap2
#      and then calls variants using GATK. These variants are then compared to a
#      drug-resistance database. We also predict the number of reads supporting drug
#      resistance variants as an insight into hetero-resistance (not applicable for minION data)
#    
#      Full documentation at https://github.com/jodyphelan/TBProfiler 
#    include:
#      - tb_profiler_profile.xml
#      - test-data
#
# DISABLED due to upstream issue
#   tb_profiler_vcf_profile:
#     description: "Predict M. tuberculosis lineage and drug resistance from variants in VCF"
#     long_description: |
#       This tool (in the TB-Profiler tool suite) takes a VCF file of M. tuberculosis variants
#       (called relative to the H37Rv reference) and predicts drug resistance from these
#       variants. 

#       Full documentation at https://github.com/jodyphelan/TBProfiler 
#     include:
#       - tb_profiler_vcf_profile.xml
#       - test-data
suite:
  name: "suite_tb_profiler"
  description: Galaxy wrapper suite for TB-Profiler and tb-profiler collate 
  long_description: |
      This suite contains Galaxy wrappers for TB-Profiler:
        - tb_profiler_profile: computes a drug resistance and lineage profile from M. tuberculosis whole genome sequencing (WGS) data. It can either work from sequence data (the tb_profiler_profile tool) or from pre-computed sequence variants in VCF format, relative to the H37Rv reference.
        - tb_profiler_collate: collate multiple JSON reports generated by tb-profiler_profile 

      Full documentation at https://github.com/jodyphelan/TBProfiler 
citations:
  - type: bibtex
    citation: "@misc{TBProfilerGitHub, title={TB-Profiler GitHub repository}, howpublished={\\url{https://github.com/jodyphelan/TBProfiler}}}"
